In [8]:
# Part A - NumPy
print("Question 1\n")
import numpy as np
arr=np.arange(1,21)
# Display the array
print("Array:",arr)
# Find the shape of the array
print("The Shape of array:",arr.shape)
# Find the maximum and minimum values
print("Maximum values:", arr.max())
print("Minimum values:",arr.min())
# Find the mean and standard deviation 
print("Mean:",arr.mean())
print("Standard Deviation:",arr.std())
# Reshape the array into 4 x 5 matrix
matrix=arr.reshape(4,5)
print("Matrix\n",matrix)
# Display the second row of the matrix
print("The second row of the matrix:",matrix[1])
# Display the third column of the matrix 
print("The third column of the matrix:",matrix[:,2])

print("\n Question 2")
import numpy as np
A=np.array([10,20,30,40,50])
B=np.array([5,10,15,20,25])
# Addition of A and B
print("Adittion of A and B:",A + B)
# Subtration of B from A
print("Subtraction of B from A:", A - B)
# Element-wise multiplication 
print("Element-wise multiplication:", A * B)
# Element-wise Division
print("Element-wise Division:", A / B)
# Find the sum of all elements in A
print("The sum of all elements in A:",A.sum())


Question 1

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
The Shape of array: (20,)
Maximum values: 20
Minimum values: 1
Mean: 10.5
Standard Deviation: 5.766281297335398
Matrix
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
The second row of the matrix: [ 6  7  8  9 10]
The third column of the matrix: [ 3  8 13 18]

 Question 2
Adittion of A and B: [15 30 45 60 75]
Subtraction of B from A: [ 5 10 15 20 25]
Element-wise multiplication: [  50  200  450  800 1250]
Element-wise Division: [2. 2. 2. 2. 2.]
The sum of all elements in A: 150


In [11]:
# Part-B Pandas
print("Question 3\n")
import pandas as pd
data = {
    "Roll No":[101,102,103,104,105],
    "Name"  : ["Ravi","Priya","Kiran","Anu","Sita"],
    "Marks" : [85,92,78,88,95]
   }
df=pd.DataFrame(data)
# Display the DataFrame
print("DataFrame\n",df)
# Display the first three records
print("The first three records:\n",df.head(3))
# Find the average marks
print("The Average Marks:",df["Marks"].mean())
# Find the student with the highest marks
print("The Student with the highest marks:\n",df.loc[df["Marks"].idxmax()])
# Find the student with the lowest marks
print("The student with the lowest marks:\n",df.loc[df["Marks"].idxmin()])
# Add a new column called "Grade"
grade = []
for m in df["Marks"]:
    if m >= 90:
        grade.append("A")
    elif m >= 80: 
        grade.append("B")
    else:
        grade.append("C")
df["Grade"] = grade
print("\nDataFrame with Grade")
print(df)


print("\n\nQuestion 4\n")
import pandas as pd
data = {
    "Product": ["Laptop","Mouse","Keyboard","Monitor"],
    "Price" : [50000,500,1200,10000],
    "Quantity":[10,50,30,15]
  }
df=pd.DataFrame(data)
print(df)
# Calculate the total value of each product
print(df["Price"]*df["Quantity"])
# Add the Total Value column
df["Total Value"]= df["Price"]*df["Quantity"]
print(df)
print("\nHighest Total Value Product:")
print(df.loc[df["Total Value"].idxmax()])
print("\nOverall Inventory Value:")
print(df["Total Value"].sum())

Question 3

DataFrame
    Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
3      104    Anu     88
4      105   Sita     95
The first three records:
    Roll No   Name  Marks
0      101   Ravi     85
1      102  Priya     92
2      103  Kiran     78
The Average Marks: 87.6
The Student with the highest marks:
 Roll No     105
Name       Sita
Marks        95
Name: 4, dtype: object
The student with the lowest marks:
 Roll No      103
Name       Kiran
Marks         78
Name: 2, dtype: object

DataFrame with Grade
   Roll No   Name  Marks Grade
0      101   Ravi     85     B
1      102  Priya     92     A
2      103  Kiran     78     C
3      104    Anu     88     B
4      105   Sita     95     A


Question 4

    Product  Price  Quantity
0    Laptop  50000        10
1     Mouse    500        50
2  Keyboard   1200        30
3   Monitor  10000        15
0    500000
1     25000
2     36000
3    150000
dtype: int64
    Product  Price  Quantity  T

In [10]:
print("\n\nQuestion 5")
import numpy as np
from sklearn.datasets import load_iris
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df["Species"]=pd.Categorical.from_codes(iris.target,iris.target_names)
print("DataFrame:")
print(df)
print("\nFirst Five Rows:")
print(df.head())
print("\nRows and Columns:")
print(df.shape)
print("\nColumn Names:")
print(df.columns)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nSummary Statistics:")
print(df.describe())
print("\nSamples in Each Class:")
print(df["Species"].value_counts())



Question 5
DataFrame:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

   